### ISSUE TITLE
Compilation error - mvn clean install -Prun-its

### ISSUE THREAD

**Issue by kbking01** [liquibase/liquibase-cosmosdb#21]
liquibase-cosmosdb/src/main/java/liquibase/ext/cosmosdb/persistence/AbstractRepository.java:[34,89] incompatible types: inference variable U has incompatible bounds
    equality constraints: T
    lower bounds: java.lang.Object
[INFO] 1 error

**Comment by alexandru-slobodcicov** [comment]
Hi @kbking01 I cannot reproduce. Please let us know the jdk version you are using or other aspects. 
Please let us know why you are trying to build, are you extending the functionality? You can use the released artifacts.

**Comment by r2liquibase** [comment]
JDK 11 and 16 is where I saw this one. #38.
